-- theater-service baseline.
--
-- Схема снята с РЕАЛЬНОЙ БД (pg_dump --schema-only), которую до этого вёл ddl-auto: update.
-- Теперь схемой владеет Flyway, Hibernate — только validate (ddl-auto: validate).
--
-- На существующей БД (таблицы уже есть, flyway_schema_history нет) Flyway с
-- baseline-on-migrate: true пометит текущее состояние как baseline v1 и НЕ будет
-- выполнять этот файл — данные сохранятся. На пустой БД (свежий том) файл выполнится
-- и создаст схему. См. application.yml.

CREATE TABLE theaters (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city    VARCHAR(255) NOT NULL
);

CREATE TABLE halls (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    theater_id BIGINT       NOT NULL,
    CONSTRAINT fk_hall_theater FOREIGN KEY (theater_id) REFERENCES theaters(id)
);

-- FK-колонку индексируем явно (её и раньше создавал @Index на сущности Hall):
-- без индекса удаление кинотеатра вызывает seq scan halls под блокировкой.
CREATE INDEX idx_hall_theater_id ON halls (theater_id);

CREATE TABLE seats (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_number  INTEGER      NOT NULL,
    seat_number INTEGER      NOT NULL,
    type        VARCHAR(255) NOT NULL,
    hall_id     BIGINT       NOT NULL,
    CONSTRAINT uk_seat_position UNIQUE (hall_id, row_number, seat_number),
    CONSTRAINT fk_seat_hall FOREIGN KEY (hall_id) REFERENCES halls(id),
    -- CHECK на enum SeatType — как его создавал Hibernate ddl-auto (для точного соответствия
    -- снятой схеме). Значения синхронны с contracts.SeatType.
    CONSTRAINT seats_type_check CHECK (type IN ('NORMAL', 'VIP', 'UNKNOWN'))
);
